### ISSUE TITLE
Archive.org

### ISSUE THREAD

**Issue by NDuma** [ipfs/archives#54] opened 2016-01-24 13:22 UTC
WebArchive

**Comment by RichardLitt** [comment] 2016-01-25 14:39
Duplicate of https://github.com/ipfs/archives/issues/39?

**Comment by NDuma** [comment] 2016-01-25 15:52
Indeed; it appears so, apologies. 
Pivot: http://www.webarchive.org.uk/ukwa/statistics

**Closed** 2016-01-25 16:00 UTC
